name: CI

concurrency:
  group: 'ci-${{ github.ref }}'
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run tests
        run: |
          go test ./... -v

